org.gradle.jvmargs=-Xmx3G
minecraft_version=1.20.1

archives_base_name=solomons_rod
mod_version=1.3.1
maven_group=net.pitan76

# https://www.curseforge.com/minecraft/mc-mods/architectury-api
architectury_version=9.1.13

# https://fabricmc.net/develop/
fabric_loader_version=0.15.6
fabric_api_version=0.92.0+1.20.1

# https://files.minecraftforge.net/
forge_version=1.20.1-47.2.20

mcpitanlib_version=+1.20.1:3.3.1
mcpitanlib_checker_version=1.0.4

changelog=Fix for MCPitanLib 3.3.1
